# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'shopListFilter' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for shopListFilter

  target 'shopListFilterTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'shopListFilterUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
