# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'shopListFilter' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # 라이브러리 경고 제거
  inhibit_all_warnings!

  # Pods for shopListFilter

  # Architecture
  pod 'ReactorKit'

  # UI
  pod 'NVActivityIndicatorView'
  
  # Rx
  pod 'RxSwift', '~> 5'
  pod 'RxCocoa', '~> 5'
  pod 'RxDataSources', '~> 4.0'

  # ETC
  pod 'EPLogger'
  pod 'ObjectMapper', '~> 3.4'
  pod 'Kingfisher', '~> 5.0'


  target 'shopListFilterTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'shopListFilterUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
